const blogs = {"b33c27e1a98011ecbeb368545a57002a": {
                    color:"#ffee58",
                    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.47784.69945075044825416.99d4e5d8-fac1-421b-8986-d0fed49db992.3cffda34-9da3-4a35-a94e-da061aa0ce7f%3Fmode%3Dscale%26q%3D90%26h%3D1080%26w%3D1920&f=1&nofb=1",
                    title: "新冠轻症是什么体验？",
                    brief: "作者在这篇文章当中回忆了新冠期间的生活及感受，并聊了聊新冠对自己的影响。",
                    date: "2022/3/21",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/covid.md",
                    },
                    "e62d9cc3a94a11ecaf6e68545a57002a": {
                    color:"#64b5f6",
                    img: "https://github.com/MohaElder/me/raw/main/src/assets/blogPics/devLogCover.png",
                    title: "Development Log of this website",
                    brief: "This blog notes the development progress of this website, including why this website exists and how does it become what you see today.",
                    date: "2022/3/19",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/DevLog.md",
                    },
                    "2d3b5e70faf311ec9fe5acde48001122": {
                    color:"#ffee58",
                    img: "https://raw.githubusercontent.com/MohaElder/me/main/src/images/20220701-_DSF5495.jpg",
                    title: "在靠近北极的镇上住一天是什么样的体验",
                    brief: "我“被迫“体验的三天隐居生活",
                    date: "2022/7/3",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/fortnelson.md",
                    },
                    "bb309f2fb17011ecbef668545a57002a": {
                    color:"#64b5f6",
                    img: "https://github.com/MohaElder/me/raw/main/src/assets/blogPics/grape_juice/grape_cover.JPG",
                    title: "[鸡酒分享] 玉光葡汁",
                    brief: "分享一款之前有一天喝酒即兴调的还不错的配方，自由度较高。",
                    date: "2022/3/31",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/jade_grape_juice.md",
                    },
                    "2d3a604cfaf311ec9fe5acde48001122": {
                    color:"#64b5f6",
                    img: "https://github.com/MohaElder/me/raw/main/src/assets/blogPics/baboa_milktea/_R006837.JPG",
                    title: "[鸡酒分享] 巴波亚奶茶",
                    brief: "分享一款奶茶酒",
                    date: "2022/4/18",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/milktea.md",
                    },
                    "d6ffad89baf711eca94e68545a57002a": {
                    color:"#64b5f6",
                    img: "https://github.com/MohaElder/me/raw/main/src/assets/blogPics/respect_women/_R006812.JPG",
                    title: "[鸡酒分享] 尊重女性",
                    brief: "分享一款作者在深夜EMO的时候即兴制作的烈酒",
                    date: "2022/4/12",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/respect_women.md",
                    },
                    "31ab9b67a63811ed8cc568545a57002a": {
                    color:"#64b5f6",
                    img: "https://picx.zhimg.com/80/v2-c37946c017304c3e7a9c2576744ac501_1440w.webp?source=1940ef5c",
                    title: "我有一台专业微单和九支镜头，我最喜欢用手机摄影",
                    brief: "作者在这篇文章当中聊了聊自己对手机摄影的理解，并分享了自己深度使用手机摄影软件Varlens的体验",
                    date: "2023/2/6",
                    article: "https://raw.githubusercontent.com/MohaElder/me/main/src/blogs/varlens.md",
                    },
                    } 
 export { blogs };