name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Use PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - id: Build-Vue
      uses: MohaElder/VuePagesAction@1.0.2
      with:
        username: 'MohaElder'
        reponame: 'me'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
