name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '19.x'
      uses: actions/setup-node@v2
      with:
        node-version: "19.x"
        cache: "npm"
    - id: Build-Vue
      uses: MohaElder/VuePagesAction@1.0.0
      with:
        username: 'MohaElder'
        reponame: 'me'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
